MODULE PRECISION
  IMPLICIT NONE
  INTEGER, PARAMETER :: SP = SELECTED_REAL_KIND (6,30)
  INTEGER, PARAMETER :: DP = SELECTED_REAL_KIND (13,60)
#IF(USE_MPI)
  INTEGER, PARAMETER :: IK = SELECTED_INT_KIND  (8)  !!! DO NOT CHANGE !!!
  INTEGER, PARAMETER :: PP = SP                      !!! DO NOT CHANGE !!!
#ELSE
  INTEGER, PARAMETER :: IK = SELECTED_INT_KIND  (8)
  INTEGER, PARAMETER :: PP = SP
#ENDIF

END MODULE PRECISION
